"""Add created_at and updated_at to Patient model

Revision ID: 29affe6bce76
Revises: 
Create Date: 2025-04-27 09:42:03.136108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29affe6bce76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('patient', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'updated_at')
    op.drop_column('patient', 'created_at')
    # ### end Alembic commands ###
